bot-token: ""
loop: false
autostart: false

commands:
  join: "!mjoin"
  leave: "!mleave"
  volume: "!mvolume"
  play: "!mplay"
  pause: "!mpause"
  skip: "!mskip"
  stop: "!mstop"
  empty: "!mempty"
  loop: "!mloop"
  save: "!msave"
  autostart: "!mauto"
  playlist: "!mplaylist"

messages:
  play: "Playing *{track}* by *{author}*..."
  pause: "Reproduction paused."
  resume: "Reproduction resumed."
  stop: "Reproduction stopped."
  loop-on: "Playlist looping has been **enabled**."
  loop-off: "Playlist looping has been **disabled**."
  autostart-on: "Autostart has been **enabled**."
  autostart-off: "Autostart has been **disabled**."
  save: "Playlist has been saved."
  playlist-add: "Adding *{track}* by *{author}* to playlist..."
  playlist-add-playlist: "Adding *{playlist}* to playlist..."
  audio-track: "{track} by {author} ({duration})"
  channel-join: "Joined the channel {channel}."
  channel-leave: "Disconnected from channel {channel}."
  not-connected: "I'm not connected to any channel."
  insufficient-perms: "I don't have permission to join this voice channel!"
  incorrect-usage: "Incorrect usage."
  internal-error: "**An error has occurred!**"
  chill-my-friend: "The bot is already trying to connect! Chill my friend!"

playlist: []